version: '2'
services:
   db:
        image: postgres:12
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - 51515:5432
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        networks:
                - alandick
   odoo:
        image: odoo:15.0
        restart: always
        ports:
                - 8069:8069
                - 8070:8069
                - 8071:8069
                - 8072:8069
                - 8072:8072
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - odoo-data:/var/lib/odoo
        networks:
                - alandick
volumes:
        odoo-data:
        db-data:
networks:
        alandick:
#    nginx:
#         image: nginx:latest
#         ports:
#                 - 80:80
#                 - 443:443
#         restart: always
#         depends_on:
#                 - odoo
#         volumes:
#                 - ./nginx/sites-enabled/:/etc/nginx/conf.d:ro
#                 # - /etc/letsencrypt:/etc/letsencrypt:ro
#         networks:
#                 - alandick